### ISSUE TITLE
mtar generated on Windows cannot be deployed when native node module is included

### ISSUE THREAD

**Issue by Kiemes** [SAP/cloud-mta-build-tool#783] opened 2020-09-25 13:56 UTC
When building an mtar with a NodeJS app on Windows and the app contains a dependency which calls `node-gyp-build` as installation instruction, e.g. [bufferutil](https://github.com/websockets/bufferutil/blob/252bd6e99eab469da6909fb6f10fba79d9e6bff2/package.json#L7) , the deployment will fail.

We created a [sample repository](https://github.wdf.sap.corp/D045390/node-gyp-issue) with which the issue can easily be reproduced. It also contains two prebuild mtar artifacts, one built on MacOSX and one built on Windows 10. You can either use those or build them again if you have those environments available. They got built with `mbt build`.

The build works fine, but the error will happen during deployment of the Windows build to CF with `cf deploy com.example.application_0.0.1-win.mtar`.
Deploying the artifact built on MacOSX works also fine on Windows.

Please provide the following info:
  - MBT Version: 1.0.16
  - OS Version: Windows 10 1909
  - If possible, provide a link to the project
https://github.wdf.sap.corp/D045390/node-gyp-issue

Steps to Reproduce:
1. `mbt build` on Windows machine of the given project
2. `cf deploy` of the mtar archive with latest cf multiapps plugin (v2.5.0)
3. observe deployment failure with error message
```
Prebuild detected (node_modules already exists)
Rebuilding any native modules
bufferutil@4.0.1 install /tmp/app/node_modules/bufferutil
node-gyp-build
sh: 1: node-gyp-build: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the bufferutil@4.0.1 install script.
...
**ERROR** Unable to build dependencies: exit status 126
ERR Failed to compile droplet: Failed to run all supply scripts: exit status 14
```

**Comment by michawai** [comment] 2020-10-20 13:10
Hi @Kiemes ,
I could not find a difference in the mtars.
The issue should be addressed first by CF-MTA deploy service.
Regards

**Comment by Kiemes** [comment] 2020-10-20 15:55
@michawai Could you please forward this to the cf mta deploy service? I don't know how to reach them. Also please link the issue here so we have a complete thread. Thx so much.

**Comment by radoslav-d** [comment] 2020-10-23 10:35
Hello @michawai,
If the Mac-build mtar gets deployed successfully and the Windows-build mtar - not, then this issue is not related to the MTA deploy service and it is most probably related to MBT or the used build/package tools. Keep in mind that the MTA deploy service does nothing with the application sources, but only gives them to the NodeJS buildpack for staging (where the error comes). I assume that the NodeJS buildpack does the same for both the Mac-build and the Windows-build mtars. What about the case in which the Windows npm adds some permission restrictions to the node_modules or something like that?
Regards,
Radoslav

**Comment by Kiemes** [comment] 2020-10-30 12:11
@michawai Since we figured out that the issue is with the mta-build tool in combination with Windows, could you please reopen the issue?
To bring the findings here, the issue is that when you do an `npm install` on a Windows machine of a node project with a dependency that calls `node-gyp-build`, it will download the binaries of node-gyp. Those binaries will not have an executable flag set in their permissions since Windows has a different permissions system then unix-like systems. Trying to execute this binary within the node buildpack will fail as this is using a linux container.

I wonder how the cf cli does this with `cf push` when running on windows, packaging everything into an archive and uploading this to CF. Are they modifying the binaries locally first before archiving? Or are they modifying the files within the archive? The archive will also be handled by the same buildpack in the same container image.

**Comment by katunin-ng** [comment] 2020-11-04 13:51
Hi, 
By design, the MTA build tool does not perform any "magic" manipulations for module builds. It just applies standard technologies commands according to the module type and then packages the build results "as is" into an MTA archive. 
By default, for nodejs modules, it applies the "npm install --production" command in the module's root folder and then takes this folder with all its content into the MTA archive. You can track this behavior via the build console output.  
If the applied command does not produce the expected results, the MTA tool cannot do anything about it. You can raise this issue to the package that has the problematic dependencies or configure a different command of your own that solves the issue.
As the issue cannot be resolved by the tool, I am closing the issue.
Regards
Natalia

**Closed by katunin-ng** 2020-11-04 13:51 UTC
