### ISSUE TITLE
NEO cli deploy-mta command fails after switch to Cloud MTA build tool 

### ISSUE THREAD

**Issue by taushanski** [SAP/cloud-mta-build-tool#630] opened 2019-12-10 10:21 UTC
Hi Colleagues,

Due to the deprecation of MTA Archive builder tool we had to switch to the new Cloud MTA build tool. I did this yesterday following the migration guide here https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool. So now the project is building fine and the mtar is being generated but when trying to deploy the generated mtar to SCP neo via NEO CLI [deploy-mta](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/1e12331df5e144c7b2cfa9f5db85d065.html) command it is failing with:

`
Deployment operation with id 'i10073' started.
11:49:05 Start deploying MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar'
11:49:05 (!) ERROR: Deploying MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar' failed: 'Invalid MTA archive [com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar].
 MTA deployment descriptor (META-INF/mtad.yaml) could not be parsed. 
For more information, see the troubleshooting section of the official documentation in the SAP Help Portal about resolving descriptor errors. Technical details: 
Invalid module [portal-deliveries] of type [com.sap.hcp.html5]: Parameter [name] is required and must have value.'
11:49:05 MTA archive 'com.sap.ibso.daikin.portal.deliveries_1.0.0.mtar' deployment finished
`
The strange thing is that the module name is exactly the same as before when the deployment was working when the mtar was built with the old tool.

For completeness i am passting the content of mta.yaml file old and new version:

* old

```yaml
_schema-version: "2.1"
ID: com.sap.ibso.daikin.portal.deliveries
version: 1.0.0
description: "Portal app for viewing deliveries information."

parameters:
  hcp-deployer-version: "1.1.0"

modules:
  - name: "portal-deliveries"
    type: html5
    path: .
    parameters:
      version: 1.0.0-${timestamp}
    build-parameters:
      builder: grunt
      grunt-opts:
        - test
        - --code-coverage
        - --force
        - build
        - regex-replace
      build-result: dist/portal-deliveries
```

* new

```yaml
_schema-version: "2.1"
ID: com.sap.ibso.daikin.portal.deliveries
version: 1.0.0
description: "Portal app for viewing deliveries information."

parameters:
  hcp-deployer-version: "1.1.0"

modules:
  - name: "portal-deliveries"
    type: html5
    path: .
    parameters:
      version: 1.0.0-${timestamp}
    build-parameters:
      builder: custom
      commands:
        - npm install
        - grunt test --code-coverage --force build regex-replace
        - npm prune --production
      build-result: dist
```

Could you please advice what could be the issue here?

**Comment by katunin-ng** [comment] 2019-12-10 10:29
Hi,

Could you please share your project git repository so we can test how the deployment descriptor is generated by the tool?

Regards
Natalia

**Comment by katunin-ng** [comment] 2019-12-10 10:31
Additional question: have you change the 'build-result' configuration in the mta.yaml on purpose?

Regards
Natalia

**Comment by taushanski** [comment] 2019-12-10 10:51
Hi @katunin-ng ,

the link to the github repo is https://github.wdf.sap.corp/DAIKIN-CommerceCustomerPortal/portal-deliveries . Its private repo so i granted you access to it. Please check **develop** branch.

Regarding why i changed the **build-result** property i thought that this is the right way to do based on https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool guide. But i tested it with both variants and the error is the same.

If you need any more information please get back to me.

Best regards,
Kiril

**Comment by katunin-ng** [comment] 2019-12-10 11:01
Hi Kiril,

Thank you for the quick response.
I will check the build and update you.

Regarding the changes in the build-result property, the recommendations in the migration guide are applicable in a case where "deploy_mode=html5-repo" which is configured as a global parameter. This case is relevant only for the deployment to CF target.  You should set your parameter according to where your grunt build generates build results that should be packaged into the mta archive. If you have not changed your grunt script, there is no reason to change this configuration.  I also do not think that this change is a reason for the current failure.

Regards
Natalia

**Comment by katunin-ng** [comment] 2019-12-10 14:14
Hi Kiril,
We identified the root cause and are going to fix the issue asap.
I will update you once the version with the fix is available.
If urgent I can suggest you a workaround based on mta extension. Let me know, please.
Regards
Natalia

**Comment by taushanski** [comment] 2019-12-10 14:29
Hi @katunin-ng ,

Thank you for the prompt reaction on this.
Do you know how much time the fix will take to be implemented?

Best regards,
Kiril

**Comment by taushanski** [comment] 2019-12-12 07:35
Hi @katunin-ng,

Could you please tell me what is workaround that you mentioned?

Best regards,
Kiril

**Comment by tal-sapan** [comment] 2019-12-12 08:24
Hi @taushanski,

For a workaround, you can add a parameter on the module called "name" with the name of the NEO application, for each html5 and Java module. It can be in an extension file if you don't want it to be in the mta.yaml.
Note that NEO application names can only contain lowercase characters and numbers (no `-` or `_`), and be up to 30 characters long.

A version with the fix should be available soon.

Best regards,
Tal

**Comment by tal-sapan** [comment] 2019-12-12 15:18
Hi,

Version 1.0.5 contains a fix for this issue. Please check.

Best regards,
Tal

**Comment by taushanski** [comment] 2019-12-13 08:31
HI @tal-sapan ,

Thank you it works with this version.
Just one question: Do you know when the XMake will switch to the new version of Cloud MTA Plugin?

Best regards,
Kiril

**Closed** 2019-12-13 20:12 UTC

**Comment by katunin-ng** [comment] 2019-12-15 06:48
Hi Kiril,

You can apply the new Build Tool in xmake if you set flag mbt-v2 to true in your .xmake.cfg file. This option is available since September this year. Moreover, this week, this flag becomes mandatory and project build will fail if the flag is not set (true/false). After January 31, 2020, xmake MTA plugin will use the new build tool only for building MTA projects. This information has been communicated by mails to xmake-users DL and to the DL of xmake MTA plugin users specifically.

Regards
Natalia

**Comment by tal-sapan** [comment] 2019-12-15 07:23
Hi Kiril,

It's now available in xmake.

Best regards,
Tal
