### ISSUE TITLE
Parameter "active" in mta.yaml is ignored

### ISSUE THREAD

**Issue by dstork** [SAP/cloud-mta-build-tool#638] opened 2019-12-19 16:42 UTC
- MBT Version: Cloud MTA Build Tool version 1.0.5
  - OS Version: Ubuntu 18.04.3 LTS
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Add a parameter "active: false" to a resource in mta.yaml
2. Build an mtar file (mbt build --mtar output.mtar)
3. In the resulting mtar, META-INF/mtad.yaml does not contain the "active" parameter

This happens regardless of the _schema-version specified in mta.yaml (2.0, 3.1.0, 3.2.0)

**Comment by tal-sapan** [comment] 2019-12-24 08:23
Hi,

The issue was fixed, please check with mbt version 1.0.6.

**Comment by katunin-ng** [comment] 2020-01-05 11:02
@dstork I am closing the issue as fixed.
Please re-open in case the problem is still reproducible with the new version.

Regards
Natalia

**Closed by katunin-ng** 2020-01-05 11:02 UTC
