### ISSUE TITLE
MTAR Build issues : Unable to build CAP Java Spring V4 Project

### ISSUE THREAD

**Issue by Showkath** [SAP/cloud-mta-build-tool#631] opened 2019-12-11 09:26 UTC
Do you want to request a feature or report a bug?
Report Bug
- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version:
  - OS Version:
  - If possible, provide a link to the project.
https://github.wdf.sap.corp/itscb/VMSCAP/tree/master/vms
Steps to Reproduce:
I followed https://sap.github.io/cloud-mta-build-tool/download/ & install all pre-requisites 
I tried to Build MTAR using below commands, all commands are giving same error 

C:\Users\i311690\git\VMSCAPGithub\vms>
1. mbt build
2. mbt build -p=cf
3.mbt build -p=cf -t .

ERROR could not build the "vms-st-db" module: could not execute the "npm install --production" command: exec: "npm": executable file not found in %PATH%
make: *** [vms-st-db] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20191210153839.mta p=cf mtar= strict=true mode=" command: exit status 2

i think issue is with vms-st-db module in yaml . Please refer my yaml file & suggest if something is incorrect
https://github.wdf.sap.corp/itscb/VMSCAP/blob/master/vms/mta.yaml

Thanks,
Showkath.

**Comment by ShimiT** [comment] 2019-12-11 09:50
It seems that you are missing npm (which is pre-requisite for building node modules) on your machine or it isn't configured properly, try to run npm install under the module path. or npm -v.

**Comment by Showkath** [comment] 2019-12-11 10:01
> npm -v
Hi ,

i ran npm -v & version is 6.13.1

**Comment by ShimiT** [comment] 2019-12-11 11:48
I think you have an issue with your environment as I was able to build your project successfully. just added .npmrc under the db module with sap registry: `@sap:registry=https://npm.sap.com/` 

[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:31 min
[INFO] Finished at: 2019-12-11T13:42:16+02:00
[INFO] ------------------------------------------------------------------------
.[2019-12-11 13:42:16]  INFO the build results of the "vms-st-srv" module will be packed and saved in the "/Users/i056926/Projects/VMSCAP/vms/.vms_mta_build_tmp/vms-st-srv" folder
[2019-12-11 13:42:16]  INFO finished building the "vms-st-srv" module
[2019-12-11 13:42:16]  INFO generating the metadata...
[2019-12-11 13:42:16]  INFO generating the MTA archive...
[2019-12-11 13:42:18]  INFO the MTA archive generated at: /Users/i056926/Projects/VMSCAP/vms/mta_archives/com.sap.cap.vms.srv_0.0.1.mtar

**Comment by katunin-ng** [comment] 2020-01-05 10:54
Hi,

I am closing the issue as not active for a few weeks.
Please re-open if the issue is still reproducible.

Regards
Natalia

**Closed by katunin-ng** 2020-01-05 10:54 UTC
